# vim:ft=kitty

# The basic colors
background_opacity 0.9

# Setting Font
font_size 14
font_family      Agave Nerd Font
bold_font        Agave Nerd Font Bold
bold_italic_font Agave Nerd Font Bold Italic

# Cursor colors

# Window settings
window_padding_width 12
cursor_trail 3

# URL underline color when hovering with mouse

# Kitty window border colors

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors

# Tab bar customization
#tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         round
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Colors for marks (marked text in the terminal)

# The 16 terminal colors

# black

# red

# green

# yellow

# blue

# magenta

# cyan

# white

# Colors: Prism Eye (matched to wallpaper)
include prism-eye.conf
